services:
  test:
    type: kubernetes-cron-job
    context: docker-desktop
    image: gcr.io/google-containers/busybox
    stages:
      production:
        cron-job-template:
          apiVersion: batch/v1beta1
          kind: CronJob
          spec:
            schedule: "*/1 * * * *"
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                    - args:
                      - /bin/sh
                      - -c
                      - date; echo Hello from the Kubernetes cluster; sleep 60
                    restartPolicy: OnFailure
